# Generated by Django 4.2.28 on 2026-02-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='territories', to='guge_app.province')),
            ],
            options={
                'unique_together': {('province', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sub_divisions', to='guge_app.division')),
            ],
            options={
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('head_name', models.CharField(max_length=255)),
                ('head_phone', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('adm_code', models.CharField(max_length=255, unique=True)),
                ('legal_reference', models.CharField(max_length=255)),
                ('secope_number', models.CharField(max_length=255)),
                ('management_regime', models.CharField(choices=[('École Non Conventionnée', 'École Non Conventionnée'), ('Catholique', 'Catholique'), ('Protestant', 'Protestant'), ('Kimbaguiste', 'Kimbaguiste'), ('Islamique', 'Islamique'), ('Salutiste', 'Salutiste'), ('Fraternité', 'Fraternité'), ('Privée', 'Privée'), ('Autres', 'Autres')], max_length=50)),
                ('mechanized_status', models.CharField(choices=[('mecanise_paye', 'Mécanisé Payé'), ('mecanise_non_paye', 'Mécanisé Non Payé'), ('non_mecanise', 'Non Mécanisé')], max_length=50)),
                ('ownership_status', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire'), ('coproprietaire', 'Copropriétaire')], max_length=50)),
                ('environment', models.CharField(choices=[('rural', 'Rural'), ('urbain', 'Urbain')], max_length=20)),
                ('geo_coord', models.JSONField(blank=True, null=True)),
                ('regroupment_center', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guge_app.city')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guge_app.division')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guge_app.province')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guge_app.subdivision')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guge_app.territory')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='divisions', to='guge_app.province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='guge_app.province'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name')},
        ),
    ]
