# Generated by Django 4.2.28 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
        migrations.RemoveField(
            model_name='province',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='province',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='population',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='principal_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='surface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
