# Generated by Django 4.2.28 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0002_remove_province_code_remove_province_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
