# Generated by Django 4.2.28 on 2026-02-23 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0004_questiontemplate_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('collector_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('pre-scolaire', 'Pré-scolaire'), ('primaire', 'preimaire'), ('secondaire', 'Secondaire')], max_length=50)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='guge_app.school')),
            ],
        ),
    ]
