# Generated by Django 4.2.28 on 2026-02-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0005_recolte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
