# Generated by Django 4.2.28 on 2026-02-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0006_alter_division_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolte',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='type',
            field=models.CharField(choices=[('pre-scolaire', 'Pré-scolaire'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='type',
            field=models.CharField(choices=[('pre-scolaire', 'Pré-scolaire'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=50),
        ),
    ]
