# Generated by Django 4.2.28 on 2026-02-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0007_recolte_status_alter_questiontemplate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='guge_app.city'),
        ),
        migrations.AlterField(
            model_name='school',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='guge_app.territory'),
        ),
    ]
