# Generated by Django 4.2.28 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0008_alter_school_city_alter_school_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sync',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
