# Generated by Django 4.2.28 on 2026-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0009_school_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='sync',
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(blank=True, choices=[('pre-scolaire', 'Pré-scolaire'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=50, null=True),
        ),
    ]
