# Generated by Django 4.2.28 on 2026-02-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guge_app', '0010_remove_school_sync_school_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recolte',
            name='collector_name',
        ),
        migrations.AddField(
            model_name='recolte',
            name='collector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
