# Generated by Django 4.2.28 on 2026-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0011_remove_recolte_collector_name_recolte_collector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
