# Generated by Django 4.2.28 on 2026-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0012_alter_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
