# Generated by Django 4.2.28 on 2026-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0013_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
    ]
