# Generated by Django 4.2.28 on 2026-02-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0015_groupe_question_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='template',
        ),
    ]
