# Generated by Django 4.2.28 on 2026-03-03  

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0017_campaign_recolte_campaign'),
    ]

    def transfer_m2m_to_fk(apps, schema_editor):
        Campaign = apps.get_model('guge_app', 'Campaign')
        # through table name automatically
        db_alias = schema_editor.connection.alias
        for campaign in Campaign.objects.using(db_alias).all():
            # pick first related template if any
            templates = campaign.question_templates.all()
            if templates:
                campaign.question_template = templates[0]
                campaign.save()

    operations = [
        # add temporary new fk field
        migrations.AddField(
            model_name='campaign',
            name='question_template',
            field=models.ForeignKey(
                related_name='campaigns_temp',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='guge_app.questiontemplate',
            ),
        ),
        # populate it from existing m2m
        migrations.RunPython(transfer_m2m_to_fk, reverse_code=migrations.RunPython.noop),
        # drop old many-to-many
        migrations.RemoveField(
            model_name='campaign',
            name='question_templates',
        ),
        # rename temporary field to correct name
        migrations.RenameField(
            model_name='campaign',
            old_name='question_template',
            new_name='question_templates',
        ),
    ]
