# Generated by Django 4.2.28 on 2026-03-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0018_alter_campaign_question_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='question_templates',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='campaigns',
                to='guge_app.questiontemplate',
            ),
        ),
    ]
