# Generated by Django 6.0.3 on 2026-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0019_alter_campaign_question_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='question_templates',
        ),
        migrations.AddField(
            model_name='campaign',
            name='question_templates',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='guge_app.questiontemplate'),
        ),
    ]
