# Generated by Django 6.0.3 on 2026-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0020_remove_campaign_question_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolte',
            name='answers',
            field=models.JSONField(blank=True),
        ),
    ]
