# Generated by Django 6.0.3 on 2026-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guge_app', '0021_alter_recolte_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolte',
            name='answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
